/*!
 * @file peinjector.h
  */
#ifndef _METERPRETER_SOURCE_EXTENSION_PEINJECTOR_H
#define _METERPRETER_SOURCE_EXTENSION_PEINJECTOR_H

#include "../../common/common.h"

#define TLV_TYPE_EXTENSION_PEINJECTOR	0

#define TLV_TYPE_PEINJECTOR_SHELLCODE      			  MAKE_CUSTOM_TLV(TLV_META_TYPE_RAW, TLV_TYPE_EXTENSION_PEINJECTOR, TLV_EXTENSIONS + 1)
#define TLV_TYPE_PEINJECTOR_SHELLCODE_SIZE      	  MAKE_CUSTOM_TLV(TLV_META_TYPE_UINT, TLV_TYPE_EXTENSION_PEINJECTOR, TLV_EXTENSIONS + 2)
#define TLV_TYPE_PEINJECTOR_SHELLCODE_ISX64      	  MAKE_CUSTOM_TLV(TLV_META_TYPE_BOOL, TLV_TYPE_EXTENSION_PEINJECTOR, TLV_EXTENSIONS + 3)
#define TLV_TYPE_PEINJECTOR_TARGET_EXECUTABLE         MAKE_CUSTOM_TLV(TLV_META_TYPE_STRING, TLV_TYPE_EXTENSION_PEINJECTOR, TLV_EXTENSIONS + 4)
#define TLV_TYPE_PEINJECTOR_RESULT         			  MAKE_CUSTOM_TLV(TLV_META_TYPE_STRING, TLV_TYPE_EXTENSION_PEINJECTOR, TLV_EXTENSIONS + 5)

#endif



