/*!
 * @file python_main.h
 * @brief Entry point and intialisation declarations for the python extension.
 */
#ifndef _METERPRETER_SOURCE_EXTENSION_PYTHON_PYTHON_MAIN_H
#define _METERPRETER_SOURCE_EXTENSION_PYTHON_PYTHON_MAIN_H

#include "../../common/common.h"

#define TLV_TYPE_EXTENSION_PYTHON	0

#define TLV_TYPE_EXTENSION_PYTHON_STRING              MAKE_CUSTOM_TLV(TLV_META_TYPE_STRING,    TLV_TYPE_EXTENSION_PYTHON, TLV_EXTENSIONS + 1)
#define TLV_TYPE_EXTENSION_PYTHON_OUTPUT              MAKE_CUSTOM_TLV(TLV_META_TYPE_STRING,    TLV_TYPE_EXTENSION_PYTHON, TLV_EXTENSIONS + 2)

#endif
