#!/usr/bin/env python3
"""Rewrite winapi_hashes.txt from the wrapper prototypes in winapi.h.

The list of DLL prefixes is auto-discovered from `#define <NAME>_DLL "…"`
in winapi.c — the same source the runtime `GetFunctionH()` uses — so
adding a new DLL group requires no changes to this script.

Usage:
    python3 tools/regen_winapi_hashes.py           # rewrite the .txt in place
    python3 tools/regen_winapi_hashes.py --check   # exit non-zero if stale
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


DLL_DEFINE_RE = re.compile(
    r'^\s*#define\s+[A-Z0-9_]+_DLL\s+"([a-z0-9_]+)\.dll"',
    re.MULTILINE,
)


def discover_dlls(winapi_c: Path) -> list[str]:
    """Return DLL prefixes in the order they appear in winapi.c."""
    text = winapi_c.read_text()
    dlls: list[str] = []
    seen: set[str] = set()
    for m in DLL_DEFINE_RE.finditer(text):
        name = m.group(1)
        if name not in seen:
            seen.add(name)
            dlls.append(name)
    if not dlls:
        raise SystemExit(f"error: no `#define <NAME>_DLL \"…\"` found in {winapi_c}")
    return dlls


def extract_prototypes(winapi_h: Path, dlls: list[str]) -> list[tuple[str, str]]:
    """Yield (dll, function) pairs in the order they appear in winapi.h.

    The DLL alternation is anchored so `ws2_32` (which contains `_`) doesn't
    get shortened to `ws2` and the leftover `32_` glued onto the function.
    """
    # Longest first — belt-and-suspenders against future prefixes that
    # could ambiguously match a shorter one (e.g. `winmm` vs `winmm_ext`).
    alt = "|".join(sorted(dlls, key=len, reverse=True))
    proto_re = re.compile(
        rf"winapi_(?P<dll>{alt})_(?P<name>[A-Za-z_0-9]+)\s*\("
    )

    pairs: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for line in winapi_h.read_text().splitlines():
        m = proto_re.search(line)
        if not m:
            continue
        key = (m.group("dll"), m.group("name"))
        if key in seen:
            continue
        seen.add(key)
        pairs.append(key)
    return pairs


def render(pairs: list[tuple[str, str]], dll_order: list[str]) -> str:
    header = (
        "# winapi_hashes.txt\n"
        "#\n"
        "# Auto-generated by tools/regen_winapi_hashes.py from source/metsrv/winapi.h.\n"
        "# Do not hand-edit; run the script again after adding/removing wrappers.\n"
        "#\n"
        "# DLL prefixes are auto-discovered from `#define <NAME>_DLL \"…\"` in\n"
        "# winapi.c. One function name per line, grouped by DLL in the order the\n"
        "# `#define`s appear. Blank lines and '#'-comments are ignored by the CMake\n"
        "# reader. See workspace/metsrv/CMakeLists.txt for the build-time _hash() port.\n"
    )
    out = [header]
    dll_to_names: dict[str, list[str]] = {d: [] for d in dll_order}
    for dll, name in pairs:
        dll_to_names[dll].append(name)
    for dll in dll_order:
        names = dll_to_names.get(dll, [])
        if not names:
            continue
        out.append(f"\n# --- {dll} ---\n")
        out.extend(f"{n}\n" for n in names)
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the on-disk file differs from the regenerated content",
    )
    args = ap.parse_args()

    here = Path(__file__).resolve().parent
    root = here.parent
    winapi_h = root / "source" / "metsrv" / "winapi.h"
    winapi_c = root / "source" / "metsrv" / "winapi.c"
    hashes_txt = root / "source" / "metsrv" / "winapi_hashes.txt"

    for f in (winapi_h, winapi_c):
        if not f.exists():
            print(f"error: cannot find {f}", file=sys.stderr)
            return 1

    dlls = discover_dlls(winapi_c)
    pairs = extract_prototypes(winapi_h, dlls)
    new = render(pairs, dlls)

    if args.check:
        old = hashes_txt.read_text() if hashes_txt.exists() else ""
        if new != old:
            print(
                f"error: {hashes_txt} is out of date; "
                f"run `python3 {Path(__file__).relative_to(root.parent)}`",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {hashes_txt} matches winapi.h ({len(pairs)} names, {len(dlls)} DLLs)")
        return 0

    hashes_txt.write_text(new)
    print(f"wrote {hashes_txt} ({len(pairs)} names, {len(dlls)} DLLs: {', '.join(dlls)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
