/*!
 * @file powershell.h
 */
#ifndef _METERPRETER_SOURCE_EXTENSION_POWERSHELL_H
#define _METERPRETER_SOURCE_EXTENSION_POWERSHELL_H

#include "../../common/common.h"

#define TLV_TYPE_EXTENSION_PSH	0

#define TLV_TYPE_POWERSHELL_SESSIONID      MAKE_CUSTOM_TLV(TLV_META_TYPE_STRING, TLV_TYPE_EXTENSION_PSH, TLV_EXTENSIONS + 1)
#define TLV_TYPE_POWERSHELL_CODE           MAKE_CUSTOM_TLV(TLV_META_TYPE_STRING, TLV_TYPE_EXTENSION_PSH, TLV_EXTENSIONS + 2)
#define TLV_TYPE_POWERSHELL_RESULT         MAKE_CUSTOM_TLV(TLV_META_TYPE_STRING, TLV_TYPE_EXTENSION_PSH, TLV_EXTENSIONS + 3)
#define TLV_TYPE_POWERSHELL_ASSEMBLY       MAKE_CUSTOM_TLV(TLV_META_TYPE_RAW,    TLV_TYPE_EXTENSION_PSH, TLV_EXTENSIONS + 5)

#endif
