# To build the dev environment.
#  docker build -t msf-ubuntu-x64-meterpreter:obfuscation -f ./Dockerfile.obfuscation .
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND noninteractive
ENV TOOLCHAIN_PREFIX=/opt/arkari-mingw
ARG TOOLCHAIN_ARCHS="i686 x86_64"
ARG DEFAULT_CRT=msvcrt
ARG CFGUARD_ARGS=""

# Other meterpreters
RUN apt-get update && \
	apt-get dist-upgrade -y && \
	apt-get -y install software-properties-common && \
	dpkg --add-architecture i386 && \
	apt-get update

RUN mkdir -p $TOOLCHAIN_PREFIX
RUN mkdir /tmp/build

RUN DEBIAN_FRONTEND="noninteractive" apt-get install -qqy --no-install-recommends \
    git wget bzip2 file unzip libtool pkg-config cmake build-essential \
    automake nasm gettext autopoint vim-tiny python3 \
    ninja-build ca-certificates curl less zip && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

RUN git clone http://github.com/jbx81-1337/arkari-mingw.git --branch=master --single-branch /tmp/build
WORKDIR /tmp/build

RUN ./build-llvm.sh $TOOLCHAIN_PREFIX && \
    ./build-lldb-mi.sh $TOOLCHAIN_PREFIX && \
    ./strip-llvm.sh $TOOLCHAIN_PREFIX && \
    ./install-wrappers.sh $TOOLCHAIN_PREFIX && \
    ./build-mingw-w64.sh $TOOLCHAIN_PREFIX --with-default-msvcrt=$DEFAULT_CRT $CFGUARD_ARGS && \
    ./build-mingw-w64-tools.sh $TOOLCHAIN_PREFIX && \
    ./build-compiler-rt.sh $TOOLCHAIN_PREFIX $CFGUARD_ARGS && \
    ./build-libcxx.sh $TOOLCHAIN_PREFIX $CFGUARD_ARGS && \
    ./build-mingw-w64-libraries.sh $TOOLCHAIN_PREFIX $CFGUARD_ARGS && \
    ./build-compiler-rt.sh $TOOLCHAIN_PREFIX --build-sanitizers && \
    ./build-openmp.sh $TOOLCHAIN_PREFIX $CFGUARD_ARGS && \
    rm -rf /build/*
ENV PATH="$TOOLCHAIN_PREFIX/bin:${PATH}"
ENV EXCLUDE_REFLECTIVE_LOADER=1
ENV LLVM_ADDITIONAL_ARGS="-Wl,--strip-all,--build-id=none,--no-insert-timestamp,--exclude-all-symbols -fmodule-name=lib.dll -O0 -Wno-macro-redefined -Wno-unused-command-line-argument -Wno-error=incompatible-pointer-types"
ENV ARKARI_ADDITIONAL_ARGS="-mllvm -irobf-indbr -mllvm -irobf-icall -mllvm -irobf-indgv -mllvm -irobf-cse -mllvm -irobf-fla"
ENV ADDITIONAL_ARGS="-DCMAKE_CXX_FLAGS=\"$LLVM_ADDITIONAL_ARGS $ARKARI_ADDITIONAL_ARGS\" -DCMAKE_C_FLAGS=\"$LLVM_ADDITIONAL_ARGS $ARKARI_ADDITIONAL_ARGS\" -DCMAKE_ASM_FLAGS=\"-O0\" -DEXCLUDE_REFLECTIVE_LOADER=ON"