#pragma once

#define USER_NORMAL_ACCOUNT				0x00000010
#define USER_DONT_EXPIRE_PASSWORD		0x00000200

#define KRB_KEY_USAGE_AS_REP_TGS_REP	2

#define DEFAULT_GROUP_ATTRIBUTES	(SE_GROUP_MANDATORY | SE_GROUP_ENABLED_BY_DEFAULT | SE_GROUP_ENABLED)
#define KIWI_NEVERTIME(filetime)	(*(PLONGLONG) filetime = MAXLONGLONG)

typedef struct _KERB_CALLBACK_CTX
{
	VOID (*pTicketHandler)(LPVOID lpContext, PKERB_TICKET_CACHE_INFO_EX pKerbTicketInfo, PKERB_EXTERNAL_TICKET pExternalTicket);
	LPVOID lpContext;
} KERB_CALLBACK_CTX, *PKERB_CALLBACK_CTX;