#ifndef _METERPRETER_COMMON_EXPORTS_H
#define _METERPRETER_COMMON_EXPORTS_H

#define EXPORT_REFLECTIVELOADER 1
#define EXPORT_INITSERVEREXTENSION 2
#define EXPORT_DEINITSERVEREXTENSION 3
#define EXPORT_STAGELESSINIT 4
#define EXPORT_COMMANDADDED 5

#endif
