/*
RtlGetCurrentPeb
LdrGetProcAddress
LdrLoadDll
RtlInitUnicodeString
RtlGetVersion
RtlInitString
RtlImageNtHeader
NtDeleteFile
NtAllocateVirualMemory
NtFreeVirtualMemory
LdrFindResource
LdrAccessResource
RtlFreeUnicodeString
RtlDOsPathNameToNtPathName
NtClose
NtOpenDirectoryObject
NtQueryDirectoryObject
NtQuerySystemInformation
NtWriteFile
NtFlushBuffersFile
NtCreateFile
*/