/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_metasploit_meterpreter_stdapi_stdapi_railgun_api */

#ifndef _Included_com_metasploit_meterpreter_stdapi_stdapi_railgun_api
#define _Included_com_metasploit_meterpreter_stdapi_stdapi_railgun_api
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_metasploit_meterpreter_stdapi_stdapi_railgun_api
 * Method:    railgunCaller
 * Signature: (I[B[B[BLjava/lang/String;Ljava/lang/String;Ljava/lang/String;[B[ILjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_metasploit_meterpreter_stdapi_stdapi_1railgun_1api_railgunCaller
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jbyteArray, jstring, jstring, jstring, jbyteArray, jintArray, jstring, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
