#pragma once
#include "../../common/common.h"

#ifndef _METERPRETER_SOURCE_EXTENSION_DRIVERTOOLS_DRIVERTOOLS_H
#define _METERPRETER_SOURCE_EXTENSION_DRIVERTOOLS_DRIVERTOOLS_H


#define TLV_TYPE_EXTENSION_DRIVERTOOLS	0

/*
*	Turla Driver Loader related TLV's
*/

#define TLV_TYPE_TDL_PCLIENT					\
	MAKE_CUSTOM_TLV(\
	TLV_META_TYPE_STRING, \
	TLV_TYPE_EXTENSION_DRIVERTOOLS, \
	TLV_EXTENSIONS + 1333)

#define TLV_TYPE_TDL_SUCCESS					\
	MAKE_CUSTOM_TLV(\
	TLV_META_TYPE_STRING, \
	TLV_TYPE_EXTENSION_DRIVERTOOLS, \
	TLV_EXTENSIONS + 1334)

#define TLV_TYPE_TDL_WARNING					\
	MAKE_CUSTOM_TLV(\
	TLV_META_TYPE_STRING, \
	TLV_TYPE_EXTENSION_DRIVERTOOLS, \
	TLV_EXTENSIONS + 1335)

#define TLV_TYPE_TDL_ERROR_MSG					\
	MAKE_CUSTOM_TLV(\
	TLV_META_TYPE_STRING, \
	TLV_TYPE_EXTENSION_DRIVERTOOLS, \
	TLV_EXTENSIONS + 1336)

#define TLV_TYPE_TDL_INJECT				\
	MAKE_CUSTOM_TLV(\
	TLV_META_TYPE_RAW, \
	TLV_TYPE_EXTENSION_DRIVERTOOLS, \
	TLV_EXTENSIONS + 1337)

#define TLV_TYPE_TDL_DRIVER_FILENAME				\
	MAKE_CUSTOM_TLV(\
	TLV_META_TYPE_STRING, \
	TLV_TYPE_EXTENSION_DRIVERTOOLS, \
	TLV_EXTENSIONS + 1339)

#endif