#ifndef _METERPRETER_SOURCE_EXTENSION_DRIVER_DRIVER_H
#define _METERPRETER_SOURCE_EXTENSION_DRIVER_DRIVER_H

#define TLV_TYPE_EXTENSION_DRIVER	0

#define TLV_TYPE_SEND_VULN					\
	MAKE_CUSTOM_TLV(\
	TLV_META_TYPE_UINT, \
	TLV_TYPE_EXTENSION_DRIVER, \
	TLV_EXTENSIONS + 1337)

#define TLV_TYPE_SET_VULN_LOC					\
	MAKE_CUSTOM_TLV(\
	TLV_META_TYPE_STRING, \
	TLV_TYPE_EXTENSION_DRIVER, \
	TLV_EXTENSIONS + 1338)

#define TLV_TYPE_DO_WORK					\
	MAKE_CUSTOM_TLV(\
	TLV_META_TYPE_RAW, \
	TLV_TYPE_EXTENSION_DRIVER, \
	TLV_EXTENSIONS + 1339)

#endif
